"""Centinela Pydantic v2 Contracts package."""

from .agentes import (
    Accion,
    AjustePrecio,
    ContactoCartera,
    CorregirVentaBajoCosto,
    DiagnosticoLLM,
    ExpeditarOC,
    ImpactoCalculado,
    ParametrosAccion,
    Propuesta,
    RenegociarProveedor,
    SeleccionAccion,
    SeleccionEstratega,
    CitaElegida,
    DiagnosticoBorrador,
    ReactivarCliente,
    RevisionDescuentos,
)
from .alertas import Alerta, AlertaVista, Hallazgo, ResumenAlertas
from .base import (
    AccionId,
    AlertaId,
    BodegaId,
    CERO_HASH,
    ClienteId,
    Confianza,
    ConsultaId,
    Contrato,
    EntidadRef,
    EstadoAlerta,
    Hash256,
    Kpi,
    OcId,
    Pesos,
    ProveedorId,
    SCHEMA_VERSION,
    Severidad,
    SkuId,
    TipoEntidad,
    TRANSICIONES,
    transicion_valida,
    VendedorId,
    Vista,
)
from .bitacora import EntradaBitacora, Evento, canonico, verificar_cadena
from .configuracion import (
    CORTE_INICIAL_LIMPIO,
    FECHA_CORTE_DEFECTO,
    ConfigUmbral,
    ConfiguracionUpdate,
    ConfiguracionVigia,
)
from .decision import Borrador, DecisionRequest, ResultadoEjecucion
from .evidencia import (
    CifraTrazable,
    CitaPolitica,
    ConsultaRegistrada,
    Unidad,
    formatear_cifra,
    numeros_en,
    numeros_sueltos,
    referencias_cifras,
    renderizar_texto,
)
from .herramientas import (
    BuscarPoliticaIn,
    BuscarPoliticaOut,
    ConsultarVistaIn,
    ConsultarVistaOut,
    CrearBorradorIn,
    Filtro,
    FragmentoPolitica,
    PipelineEvent,
)
from .operacion import (
    ChatCifra,
    ChatError,
    ChatEvento,
    ChatFin,
    ChatGrafico,
    ChatPaso,
    ChatRequest,
    CostoAgente,
    ResumenCostos,
    ChatToken,
    PuntoGrafico,
    RefCifra,
    RefGrafico,
    RespuestaChat,
    ErrorAPI,
    SimulacionResp,
    TrazaLLM,
)

__all__ = [
    # Base
    "Contrato",
    "ClienteId",
    "SkuId",
    "VendedorId",
    "ProveedorId",
    "BodegaId",
    "OcId",
    "AlertaId",
    "ConsultaId",
    "AccionId",
    "Hash256",
    "Pesos",
    "Confianza",
    "CERO_HASH",
    "SCHEMA_VERSION",
    "Kpi",
    "Vista",
    "Severidad",
    "EstadoAlerta",
    "TRANSICIONES",
    "TipoEntidad",
    "EntidadRef",
    "transicion_valida",
    # Evidencia
    "Unidad",
    "ConsultaRegistrada",
    "CifraTrazable",
    "CitaPolitica",
    "numeros_sueltos",
    "referencias_cifras",
    "renderizar_texto",
    "formatear_cifra",
    "numeros_en",
    # Alertas
    "Hallazgo",
    "Alerta",
    "AlertaVista",
    "ResumenAlertas",
    # Agentes
    "DiagnosticoLLM",
    "AjustePrecio",
    "ContactoCartera",
    "ExpeditarOC",
    "RevisionDescuentos",
    "ReactivarCliente",
    "CorregirVentaBajoCosto",
    "ParametrosAccion",
    "RenegociarProveedor",
    "SeleccionAccion",
    "SeleccionEstratega",
    "CitaElegida",
    "DiagnosticoBorrador",
    "ImpactoCalculado",
    "Accion",
    "Propuesta",
    # Decision
    "DecisionRequest",
    "Borrador",
    "ResultadoEjecucion",
    # Bitacora
    "Evento",
    "canonico",
    "EntradaBitacora",
    "verificar_cadena",
    # Operacion
    "TrazaLLM",
    "ChatRequest",
    "CostoAgente",
    "ResumenCostos",
    "ChatToken",
    "ChatCifra",
    "ChatFin",
    "ChatError",
    "ChatEvento",
    "ChatGrafico",
    "ChatPaso",
    "PuntoGrafico",
    "RefCifra",
    "RefGrafico",
    "RespuestaChat",
    "ErrorAPI",
    "SimulacionResp",
    # Herramientas
    "Filtro",
    "ConsultarVistaIn",
    "ConsultarVistaOut",
    "BuscarPoliticaIn",
    "FragmentoPolitica",
    "BuscarPoliticaOut",
    "CrearBorradorIn",
    "PipelineEvent",
    # Configuracion
    "ConfigUmbral",
    "ConfiguracionVigia",
    "ConfiguracionUpdate",
    "CORTE_INICIAL_LIMPIO",
    "FECHA_CORTE_DEFECTO",
]

