"""Centinela Pydantic v2 Contracts package."""

from .agentes import (
    Accion,
    AccionLLM,
    AjustePrecio,
    ContactoCartera,
    CorregirVentaBajoCosto,
    DiagnosticoLLM,
    ExpeditarOC,
    ImpactoCalculado,
    ParametrosAccion,
    Propuesta,
    PropuestaLLM,
    ReactivarCliente,
    RevisionDescuentos,
)
from .alertas import Alerta, AlertaVista, Hallazgo
from .base import (
    AccionId,
    AlertaId,
    BodegaId,
    CERO_HASH,
    ClienteId,
    Confianza,
    ConsultaId,
    Contrato,
    EntidadRef,
    EstadoAlerta,
    Hash256,
    Kpi,
    OcId,
    Pesos,
    ProveedorId,
    SCHEMA_VERSION,
    Severidad,
    SkuId,
    TipoEntidad,
    TRANSICIONES,
    transicion_valida,
    VendedorId,
    Vista,
)
from .bitacora import EntradaBitacora, Evento, canonico, verificar_cadena
from .configuracion import CORTE_INICIAL_LIMPIO, FECHA_CORTE_DEFECTO, CentinelaConfig, ConfigKpi
from .decision import Borrador, DecisionRequest, ResultadoEjecucion
from .evidencia import CifraTrazable, CitaPolitica, ConsultaRegistrada, Unidad, numeros_sueltos
from .herramientas import (
    BuscarPoliticaIn,
    BuscarPoliticaOut,
    CalcularImpactoIn,
    ConsultarVistaIn,
    ConsultarVistaOut,
    CrearBorradorIn,
    EstadoGrafo,
    Filtro,
    FragmentoPolitica,
    InterruptPayload,
    PipelineEvent,
)
from .operacion import (
    ChatCifra,
    ChatError,
    ChatEvento,
    ChatFin,
    ChatRequest,
    ChatToken,
    ErrorAPI,
    SimulacionResp,
    TrazaLLM,
)

__all__ = [
    # Base
    "Contrato",
    "ClienteId",
    "SkuId",
    "VendedorId",
    "ProveedorId",
    "BodegaId",
    "OcId",
    "AlertaId",
    "ConsultaId",
    "AccionId",
    "Hash256",
    "Pesos",
    "Confianza",
    "CERO_HASH",
    "SCHEMA_VERSION",
    "Kpi",
    "Vista",
    "Severidad",
    "EstadoAlerta",
    "TRANSICIONES",
    "TipoEntidad",
    "EntidadRef",
    "transicion_valida",
    # Evidencia
    "Unidad",
    "ConsultaRegistrada",
    "CifraTrazable",
    "CitaPolitica",
    "numeros_sueltos",
    # Alertas
    "Hallazgo",
    "Alerta",
    "AlertaVista",
    # Agentes
    "DiagnosticoLLM",
    "AjustePrecio",
    "ContactoCartera",
    "ExpeditarOC",
    "RevisionDescuentos",
    "ReactivarCliente",
    "CorregirVentaBajoCosto",
    "ParametrosAccion",
    "AccionLLM",
    "PropuestaLLM",
    "ImpactoCalculado",
    "Accion",
    "Propuesta",
    # Decision
    "DecisionRequest",
    "Borrador",
    "ResultadoEjecucion",
    # Bitacora
    "Evento",
    "canonico",
    "EntradaBitacora",
    "verificar_cadena",
    # Operacion
    "TrazaLLM",
    "ChatRequest",
    "ChatToken",
    "ChatCifra",
    "ChatFin",
    "ChatError",
    "ChatEvento",
    "ErrorAPI",
    "SimulacionResp",
    # Herramientas
    "Filtro",
    "ConsultarVistaIn",
    "ConsultarVistaOut",
    "BuscarPoliticaIn",
    "FragmentoPolitica",
    "BuscarPoliticaOut",
    "CalcularImpactoIn",
    "CrearBorradorIn",
    "EstadoGrafo",
    "InterruptPayload",
    "PipelineEvent",
    # Configuracion
    "ConfigKpi",
    "CentinelaConfig",
    "CORTE_INICIAL_LIMPIO",
    "FECHA_CORTE_DEFECTO",
]

